/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UmumiyRouteImport } from './routes/umumiy'
import { Route as TovarlarRouteImport } from './routes/tovarlar'
import { Route as SozlamalarRouteImport } from './routes/sozlamalar'
import { Route as MijozlarRouteImport } from './routes/mijozlar'
import { Route as KassaRouteImport } from './routes/kassa'
import { Route as IndexRouteImport } from './routes/index'

const UmumiyRoute = UmumiyRouteImport.update({
  id: '/umumiy',
  path: '/umumiy',
  getParentRoute: () => rootRouteImport,
} as any)
const TovarlarRoute = TovarlarRouteImport.update({
  id: '/tovarlar',
  path: '/tovarlar',
  getParentRoute: () => rootRouteImport,
} as any)
const SozlamalarRoute = SozlamalarRouteImport.update({
  id: '/sozlamalar',
  path: '/sozlamalar',
  getParentRoute: () => rootRouteImport,
} as any)
const MijozlarRoute = MijozlarRouteImport.update({
  id: '/mijozlar',
  path: '/mijozlar',
  getParentRoute: () => rootRouteImport,
} as any)
const KassaRoute = KassaRouteImport.update({
  id: '/kassa',
  path: '/kassa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kassa': typeof KassaRoute
  '/mijozlar': typeof MijozlarRoute
  '/sozlamalar': typeof SozlamalarRoute
  '/tovarlar': typeof TovarlarRoute
  '/umumiy': typeof UmumiyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kassa': typeof KassaRoute
  '/mijozlar': typeof MijozlarRoute
  '/sozlamalar': typeof SozlamalarRoute
  '/tovarlar': typeof TovarlarRoute
  '/umumiy': typeof UmumiyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kassa': typeof KassaRoute
  '/mijozlar': typeof MijozlarRoute
  '/sozlamalar': typeof SozlamalarRoute
  '/tovarlar': typeof TovarlarRoute
  '/umumiy': typeof UmumiyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kassa'
    | '/mijozlar'
    | '/sozlamalar'
    | '/tovarlar'
    | '/umumiy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kassa' | '/mijozlar' | '/sozlamalar' | '/tovarlar' | '/umumiy'
  id:
    | '__root__'
    | '/'
    | '/kassa'
    | '/mijozlar'
    | '/sozlamalar'
    | '/tovarlar'
    | '/umumiy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KassaRoute: typeof KassaRoute
  MijozlarRoute: typeof MijozlarRoute
  SozlamalarRoute: typeof SozlamalarRoute
  TovarlarRoute: typeof TovarlarRoute
  UmumiyRoute: typeof UmumiyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/umumiy': {
      id: '/umumiy'
      path: '/umumiy'
      fullPath: '/umumiy'
      preLoaderRoute: typeof UmumiyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tovarlar': {
      id: '/tovarlar'
      path: '/tovarlar'
      fullPath: '/tovarlar'
      preLoaderRoute: typeof TovarlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sozlamalar': {
      id: '/sozlamalar'
      path: '/sozlamalar'
      fullPath: '/sozlamalar'
      preLoaderRoute: typeof SozlamalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mijozlar': {
      id: '/mijozlar'
      path: '/mijozlar'
      fullPath: '/mijozlar'
      preLoaderRoute: typeof MijozlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kassa': {
      id: '/kassa'
      path: '/kassa'
      fullPath: '/kassa'
      preLoaderRoute: typeof KassaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KassaRoute: KassaRoute,
  MijozlarRoute: MijozlarRoute,
  SozlamalarRoute: SozlamalarRoute,
  TovarlarRoute: TovarlarRoute,
  UmumiyRoute: UmumiyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
